version: '3.8'

services:
  backend:
    build:
      context: ./respondio-api
    container_name: respondio-backend
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_DATABASE=respondio
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  frontend:
    build:
      context: ./respondio-www
    container_name: respondio-frontend
    ports:
      - "3001:80"
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: respondio-mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: respondio
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  # Redis server
  redis:
    image: redis:alpine
    container_name: respondio-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
